// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdsdGHF8gph0UD_8TBfAxWxnbW5Ay6QE8',
    appId: '1:250598497135:web:b2faf3d8d32b4652f4269a',
    messagingSenderId: '250598497135',
    projectId: 'fir-dbf45',
    authDomain: 'fir-dbf45.firebaseapp.com',
    storageBucket: 'fir-dbf45.appspot.com',
    measurementId: 'G-B0MTFDV30N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvk45B2suJzCKXC5lyWnA8K_ZciWzW5MI',
    appId: '1:250598497135:android:1c6598afd7b3e9d2f4269a',
    messagingSenderId: '250598497135',
    projectId: 'fir-dbf45',
    storageBucket: 'fir-dbf45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADnNsiDmZac33Vk0Zt9YVff95FevIUp7k',
    appId: '1:250598497135:ios:3062a66f46943763f4269a',
    messagingSenderId: '250598497135',
    projectId: 'fir-dbf45',
    storageBucket: 'fir-dbf45.appspot.com',
    iosClientId: '250598497135-t4vi9rkj176lpd87ceh9mib7oo5emfpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADnNsiDmZac33Vk0Zt9YVff95FevIUp7k',
    appId: '1:250598497135:ios:3062a66f46943763f4269a',
    messagingSenderId: '250598497135',
    projectId: 'fir-dbf45',
    storageBucket: 'fir-dbf45.appspot.com',
    iosClientId: '250598497135-t4vi9rkj176lpd87ceh9mib7oo5emfpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
